Repository Ashpara10/acm-website, pull requests merged in 2024-10, with the labels that each got.

#7 Issue #5 - [ENHANCEMENT] Replace Socials with Icons in Footer
  src/components/icons/discord-icon.tsx
  src/components/icons/instagram-icon.tsx
  src/components/icons/whatsapp-icon.tsx
  src/components/layout/sections/Community.tsx
  src/components/layout/sections/Footer.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#17 Issue #10 fixed the code to use icons dynamically
  src/components/icons/discord-icon.tsx
  src/components/icons/github-icon.tsx
  src/components/icons/instagram-icon.tsx
  src/components/icons/linkedin-icon.tsx
  src/components/icons/whatsapp-icon.tsx
  src/components/icons/x-icon.tsx
  src/components/layout/sections/Community.tsx
  src/components/layout/sections/Team.tsx
Labels: hacktoberfest-accepted

#21 [PRODUCTION FIX] Issue #20 Type Validation & Linting Issue
  package-lock.json
  package.json
  src/app/events/page.tsx
  src/components/event-page.tsx
  src/components/layout/navbar.tsx
  src/components/layout/sections/About.tsx
  src/components/layout/sections/Footer.tsx
  src/components/layout/sections/Hero.tsx
  src/components/layout/sections/Sponsors.tsx
  src/components/ui/accordion.tsx
  src/components/ui/input.tsx
  src/components/ui/textarea.tsx
  src/lib/utils.ts
Labels: hacktoberfest-accepted

#23 Issue #22 fixed [BUG] JS Error of Hydration occurring on Events Page
  src/components/event-card.tsx
Labels: hacktoberfest-accepted

#25 Issue #24 [FEATURE] To Add Top 3 Events on Home Page
  src/app/page.tsx
  src/components/layout/sections/Events.tsx
  src/components/layout/sections/Sponsors.tsx
  src/lib/utils.ts
Labels: hacktoberfest, hacktoberfest-accepted

#27 Issue #26 [FEATURE] To Add Indicator Badge on Event Cards
  src/components/event-card.tsx
  src/data/events/ainnovate.md
  src/data/events/basics-of-javascript.md
  src/data/events/conquering-canva.md
  src/data/events/digital-marketing.md
  src/data/events/fastn-workshop.md
  src/data/events/fundamentals-of-video-editing.md
  src/data/events/technical-tambola.md
  src/lib/types.ts
Labels: hacktoberfest, hacktoberfest-accepted

#31 Added Mentors Section on Website 👨‍💻
  public/mentors/abbas.jpeg
  public/mentors/archi.jpeg
  public/mentors/lakshay.jpeg
  public/mentors/mayank.jpeg
  public/mentors/murtaza.jpeg
  public/mentors/murtaza.jpg
  public/mentors/ram.jpg
  src/app/page.tsx
  src/components/layout/sections/Mentors.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#35 Updated hover effect: affected files - event-card.tsx
  next.config.mjs
  src/components/event-card.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#38 Issue #37 [ENHANCEMENT] To replace dummy executive data with actual one.
  src/data/team/ExecutiveTeam.data.md
Labels: hacktoberfest-accepted

#41 [ISSUE] To Remove Redundant Use of Footer in Each Route #40
  src/app/events/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/team/page.tsx
Labels: hacktoberfest-accepted

#44 [ISSUE] Favicon Not Visible on All Routes #42
  src/app/favicon.ico
  src/app/icon.png
  src/app/page.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#54 Added anchor tag after the events section
  src/components/layout/sections/Events.tsx
Labels: hacktoberfest-accepted

#56 Resolves #51 : Top Contributors section added
  .gitignore
  next.config.mjs
  src/app/page.tsx
  src/components/layout/sections/TopContributors.tsx
  src/components/top-contributor-card.tsx
  src/lib/utils.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#58 Fixed Hover on executive card
  src/components/layout/sections/Events.tsx
  src/components/layout/sections/ExecutiveTeamSection/ExecutiveMemberCard.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#73 Added Blur fade Animation 🛩️
  package-lock.json
  package.json
  src/components/layout/navbar.tsx
  src/components/layout/sections/About.tsx
  src/components/layout/sections/Community.tsx
  src/components/layout/sections/ContributorsSection/index.tsx
  src/components/layout/sections/CoreCouncil.tsx
  src/components/layout/sections/Events.tsx
  src/components/layout/sections/Faq.tsx
  src/components/layout/sections/Footer.tsx
  src/components/layout/sections/Hero.tsx
  src/components/layout/sections/Mentors.tsx
  src/components/layout/sections/Sponsors.tsx
  src/components/layout/sections/Testimonial.tsx
  src/components/layout/sections/TextHoverEffectSection.tsx
  src/components/ui/BlurFade.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#74 [ENHANCEMENT] Adding Hover effect on the Socials in the Team and Mentors Cards #71
  src/components/layout/sections/CoreCouncil.tsx
  src/components/layout/sections/Mentors.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#77 Fixes #68 : Inconsistencies in Testimonials Section fixed
  src/components/layout/sections/CoreCouncil.tsx
  src/components/layout/sections/Events.tsx
  src/components/layout/sections/Testimonial.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#78 Resolves #69 : Updated Carousel Images to Event-Specific Images
  public/events/basics-of-javascript/js-1.jpg
  public/events/basics-of-javascript/js-2.jpg
  public/events/basics-of-javascript/js-3.jpg
  src/data/events/basics-of-javascript.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#82 Resolves #80 : Added glassmorphism effect to navbar and reduced delay on BlurFade component
  public/events/basics-of-javascript/js-1.jpeg
  public/events/basics-of-javascript/js-2.jpeg
  public/events/basics-of-javascript/js-3.jpeg
  src/components/layout/navbar.tsx
  src/components/ui/BlurFade.tsx
Labels: hacktoberfest, hacktoberfest-accepted
